//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        internal static string Address1 {
            get {
                return ResourceManager.GetString("Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to commpare list.
        /// </summary>
        internal static string addToCompareList {
            get {
                return ResourceManager.GetString("addToCompareList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read,understand and agree with the applicable Booking Conditions.
        /// </summary>
        internal static string agreeTermCondition {
            get {
                return ResourceManager.GetString("agreeTermCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airline ticket.
        /// </summary>
        internal static string airticket {
            get {
                return ResourceManager.GetString("airticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount with VAT.
        /// </summary>
        internal static string amountWithVAT {
            get {
                return ResourceManager.GetString("amountWithVAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquila Booking.
        /// </summary>
        internal static string aquilaBooking {
            get {
                return ResourceManager.GetString("aquilaBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string available {
            get {
                return ResourceManager.GetString("available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số dư.
        /// </summary>
        internal static string balanceQuantity {
            get {
                return ResourceManager.GetString("balanceQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AB bank.
        /// </summary>
        internal static string bankAB {
            get {
                return ResourceManager.GetString("bankAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia Commercial Bank (ACB).
        /// </summary>
        internal static string bankACB {
            get {
                return ResourceManager.GetString("bankACB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank account name.
        /// </summary>
        internal static string bankAccountName {
            get {
                return ResourceManager.GetString("bankAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank account number.
        /// </summary>
        internal static string bankAccountNumber {
            get {
                return ResourceManager.GetString("bankAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGRIBANK branch 3.
        /// </summary>
        internal static string bankAGRI {
            get {
                return ResourceManager.GetString("bankAGRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngân hàng Đông Á.
        /// </summary>
        internal static string bankDongA {
            get {
                return ResourceManager.GetString("bankDongA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mekong Development Bank (MDB).
        /// </summary>
        internal static string bankMDB {
            get {
                return ResourceManager.GetString("bankMDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        internal static string bankName {
            get {
                return ResourceManager.GetString("bankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sacombank Au Co branch.
        /// </summary>
        internal static string bankSACOM {
            get {
                return ResourceManager.GetString("bankSACOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sacombank Tan Phu branch.
        /// </summary>
        internal static string bankSACOM1 {
            get {
                return ResourceManager.GetString("bankSACOM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VietComBank (VCB).
        /// </summary>
        internal static string bankVCB {
            get {
                return ResourceManager.GetString("bankVCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số dư đầu kỳ.
        /// </summary>
        internal static string beginBalance {
            get {
                return ResourceManager.GetString("beginBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking code.
        /// </summary>
        internal static string bookingCode {
            get {
                return ResourceManager.GetString("bookingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking condition.
        /// </summary>
        internal static string bookingCondition {
            get {
                return ResourceManager.GetString("bookingCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking date.
        /// </summary>
        internal static string bookingDate {
            get {
                return ResourceManager.GetString("bookingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availibity details.
        /// </summary>
        internal static string BookingDetails {
            get {
                return ResourceManager.GetString("BookingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your booking history.
        /// </summary>
        internal static string bookingHistory {
            get {
                return ResourceManager.GetString("bookingHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking status.
        /// </summary>
        internal static string bookingStatus {
            get {
                return ResourceManager.GetString("bookingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking summary.
        /// </summary>
        internal static string bookingSummary {
            get {
                return ResourceManager.GetString("bookingSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOK NOW.
        /// </summary>
        internal static string Booknow {
            get {
                return ResourceManager.GetString("Booknow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter number of rooms you want to book.
        /// </summary>
        internal static string bookwarningNofRoom {
            get {
                return ResourceManager.GetString("bookwarningNofRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mua.
        /// </summary>
        internal static string buy {
            get {
                return ResourceManager.GetString("buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping cart.
        /// </summary>
        internal static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquila System thông báo: Thay đổi mật khẩu.
        /// </summary>
        internal static string changePassEmailSubject {
            get {
                return ResourceManager.GetString("changePassEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password.
        /// </summary>
        internal static string changePassword {
            get {
                return ResourceManager.GetString("changePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu thành công.
        /// </summary>
        internal static string changePasswordSuccessfully {
            get {
                return ResourceManager.GetString("changePasswordSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu của Quý khách đã được thay đổi thành công. Mật khẩu mới đã được gửi vào hộp thư của Quý khách. Vui lòng kiểm tra email để biết thông tin mật khẩu mới..
        /// </summary>
        internal static string changePasswordSuccessMessage {
            get {
                return ResourceManager.GetString("changePasswordSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can check your booking by clicking .
        /// </summary>
        internal static string checkBookingNotify01 {
            get {
                return ResourceManager.GetString("checkBookingNotify01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  or go to the booking history to view your booking.
        /// </summary>
        internal static string checkBookingNotify02 {
            get {
                return ResourceManager.GetString("checkBookingNotify02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select check in date.
        /// </summary>
        internal static string checkinDateTitle {
            get {
                return ResourceManager.GetString("checkinDateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click vào đây để kiểm tra lịch sử đặt phòng.
        /// </summary>
        internal static string CheckingHotelBooking {
            get {
                return ResourceManager.GetString("CheckingHotelBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select check out date.
        /// </summary>
        internal static string checkoutDateTitle {
            get {
                return ResourceManager.GetString("checkoutDateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price checking.
        /// </summary>
        internal static string checkPrice {
            get {
                return ResourceManager.GetString("checkPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your booking.
        /// </summary>
        internal static string checkYourBooking {
            get {
                return ResourceManager.GetString("checkYourBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        internal static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare list.
        /// </summary>
        internal static string CompareList {
            get {
                return ResourceManager.GetString("CompareList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string confirmPass {
            get {
                return ResourceManager.GetString("confirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        internal static string confirmPasswordNotMatch {
            get {
                return ResourceManager.GetString("confirmPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify your confirm password.
        /// </summary>
        internal static string confirmPasswordRequired {
            get {
                return ResourceManager.GetString("confirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where to find us.
        /// </summary>
        internal static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREDIT CARD.
        /// </summary>
        internal static string creditCard {
            get {
                return ResourceManager.GetString("creditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tăng.
        /// </summary>
        internal static string creditDescription {
            get {
                return ResourceManager.GetString("creditDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người mua.
        /// </summary>
        internal static string creditShareHolderCode {
            get {
                return ResourceManager.GetString("creditShareHolderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người mua.
        /// </summary>
        internal static string creditShareHolderName {
            get {
                return ResourceManager.GetString("creditShareHolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        internal static string currentPassword {
            get {
                return ResourceManager.GetString("currentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR INFORMATION.
        /// </summary>
        internal static string customerInfo {
            get {
                return ResourceManager.GetString("customerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOMESTIC DEBIT CARD.
        /// </summary>
        internal static string debitCard {
            get {
                return ResourceManager.GetString("debitCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giảm.
        /// </summary>
        internal static string debitDescription {
            get {
                return ResourceManager.GetString("debitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người bán.
        /// </summary>
        internal static string debitShareHolderCode {
            get {
                return ResourceManager.GetString("debitShareHolderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người bán.
        /// </summary>
        internal static string debitShareHolderName {
            get {
                return ResourceManager.GetString("debitShareHolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string deleteComment {
            get {
                return ResourceManager.GetString("deleteComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove comment.
        /// </summary>
        internal static string deleteCommentTitle {
            get {
                return ResourceManager.GetString("deleteCommentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this comment?.
        /// </summary>
        internal static string deleteCommentYN {
            get {
                return ResourceManager.GetString("deleteCommentYN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit amount.
        /// </summary>
        internal static string depositAmount {
            get {
                return ResourceManager.GetString("depositAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your destination.
        /// </summary>
        internal static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your destination to search.
        /// </summary>
        internal static string destinationMising {
            get {
                return ResourceManager.GetString("destinationMising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking details.
        /// </summary>
        internal static string DetailBooking {
            get {
                return ResourceManager.GetString("DetailBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel details.
        /// </summary>
        internal static string DetailHotel {
            get {
                return ResourceManager.GetString("DetailHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dometic Hotels.
        /// </summary>
        internal static string dometicHotel {
            get {
                return ResourceManager.GetString("dometicHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        internal static string emailAddress {
            get {
                return ResourceManager.GetString("emailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in your email address.
        /// </summary>
        internal static string EmailAddressRequired {
            get {
                return ResourceManager.GetString("EmailAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address is not valid, please provide an valid email address (abc@abc.com.vn) with a least 8 charaters length..
        /// </summary>
        internal static string emailFormatError {
            get {
                return ResourceManager.GetString("emailFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email bị trùng hoặc không đúng định dạng, ví dụ: abc@xyz.com.
        /// </summary>
        internal static string ErrorEmail {
            get {
                return ResourceManager.GetString("ErrorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate check-in time.
        /// </summary>
        internal static string estimateArrivalTime {
            get {
                return ResourceManager.GetString("estimateArrivalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ(s).
        /// </summary>
        internal static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite destinations.
        /// </summary>
        internal static string FavouritDestination {
            get {
                return ResourceManager.GetString("FavouritDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name:.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2012 - Công ty cổ phần Chứng Khoán Nhất Việt.
        /// </summary>
        internal static string footerText {
            get {
                return ResourceManager.GetString("footerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        internal static string forgotPass {
            get {
                return ResourceManager.GetString("forgotPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu?.
        /// </summary>
        internal static string forgotpassword {
            get {
                return ResourceManager.GetString("forgotpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-in.
        /// </summary>
        internal static string fromDate {
            get {
                return ResourceManager.GetString("fromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date.
        /// </summary>
        internal static string FromDate1 {
            get {
                return ResourceManager.GetString("FromDate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check-out date has to be later than check-in date.
        /// </summary>
        internal static string fromDateGreaterToDate {
            get {
                return ResourceManager.GetString("fromDateGreaterToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        internal static string fullName {
            get {
                return ResourceManager.GetString("fullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your full name has to be at least 12 charaters.
        /// </summary>
        internal static string fullNameMinimumLength {
            get {
                return ResourceManager.GetString("fullNameMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in your full name.
        /// </summary>
        internal static string fullNameRequired {
            get {
                return ResourceManager.GetString("fullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string goBack {
            get {
                return ResourceManager.GetString("goBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhấp chuột để  về trước.
        /// </summary>
        internal static string goBackHint {
            get {
                return ResourceManager.GetString("goBackHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng dẫn sử dụng.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help1 {
            get {
                return ResourceManager.GetString("Help1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help from Aquila.
        /// </summary>
        internal static string HelpFromUs {
            get {
                return ResourceManager.GetString("HelpFromUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        internal static string here {
            get {
                return ResourceManager.GetString("here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aquila.com.vn: online hotel reservation, online hotel booking.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home1 {
            get {
                return ResourceManager.GetString("Home1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking review.
        /// </summary>
        internal static string hotelBookingReview {
            get {
                return ResourceManager.GetString("hotelBookingReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hotel photo.
        /// </summary>
        internal static string hotelImage {
            get {
                return ResourceManager.GetString("hotelImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel name.
        /// </summary>
        internal static string HotelName {
            get {
                return ResourceManager.GetString("HotelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services offered by.
        /// </summary>
        internal static string hotelServices {
            get {
                return ResourceManager.GetString("hotelServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star.
        /// </summary>
        internal static string HotelStar {
            get {
                return ResourceManager.GetString("HotelStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent viewed hotels.
        /// </summary>
        internal static string HotelViewlastest {
            get {
                return ResourceManager.GetString("HotelViewlastest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to pay.
        /// </summary>
        internal static string howToPay {
            get {
                return ResourceManager.GetString("howToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo of: .
        /// </summary>
        internal static string imagesOf {
            get {
                return ResourceManager.GetString("imagesOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login name or password not valid.
        /// </summary>
        internal static string incorrectUserNamePassword {
            get {
                return ResourceManager.GetString("incorrectUserNamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International Hotels.
        /// </summary>
        internal static string internationalHotel {
            get {
                return ResourceManager.GetString("internationalHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ không đúng.
        /// </summary>
        internal static string InvalidOldPassword {
            get {
                return ResourceManager.GetString("InvalidOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip Address.
        /// </summary>
        internal static string ipAddress {
            get {
                return ResourceManager.GetString("ipAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is enable.
        /// </summary>
        internal static string isEnable {
            get {
                return ResourceManager.GetString("isEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LangE {
            get {
                return ResourceManager.GetString("LangE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng việt.
        /// </summary>
        internal static string LangV {
            get {
                return ResourceManager.GetString("LangV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last login date.
        /// </summary>
        internal static string lastLoginDate {
            get {
                return ResourceManager.GetString("lastLoginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name:.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DANH MỤC PHÒNG.
        /// </summary>
        internal static string ListRoom {
            get {
                return ResourceManager.GetString("ListRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string loginId {
            get {
                return ResourceManager.GetString("loginId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login name must be at least 6 charaters length.
        /// </summary>
        internal static string loginNameMinimumLength {
            get {
                return ResourceManager.GetString("loginNameMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login ID is required to fill in.
        /// </summary>
        internal static string loginNameRequired {
            get {
                return ResourceManager.GetString("loginNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát.
        /// </summary>
        internal static string logOff {
            get {
                return ResourceManager.GetString("logOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhấp chuột để đăng xuất.
        /// </summary>
        internal static string logOffHint {
            get {
                return ResourceManager.GetString("logOffHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log on.
        /// </summary>
        internal static string logOn {
            get {
                return ResourceManager.GetString("logOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed, please fill in the below required information to login again.
        /// </summary>
        internal static string logonFailed {
            get {
                return ResourceManager.GetString("logonFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhấp chuột để đăng nhập.
        /// </summary>
        internal static string logonHint {
            get {
                return ResourceManager.GetString("logonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to.
        /// </summary>
        internal static string logonNeeded {
            get {
                return ResourceManager.GetString("logonNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So sánh.
        /// </summary>
        internal static string LowerCompare {
            get {
                return ResourceManager.GetString("LowerCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your hotel booking information has been sent to you by email. Please check your email for booking details. .
        /// </summary>
        internal static string mailToClient {
            get {
                return ResourceManager.GetString("mailToClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string map {
            get {
                return ResourceManager.GetString("map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show map of .
        /// </summary>
        internal static string mapTitle {
            get {
                return ResourceManager.GetString("mapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tối đa.
        /// </summary>
        internal static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number.
        /// </summary>
        internal static string mobile {
            get {
                return ResourceManager.GetString("mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most viewed.
        /// </summary>
        internal static string MostView {
            get {
                return ResourceManager.GetString("MostView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login account.
        /// </summary>
        internal static string myProfile {
            get {
                return ResourceManager.GetString("myProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile.
        /// </summary>
        internal static string myProfile1 {
            get {
                return ResourceManager.GetString("myProfile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string newPassword {
            get {
                return ResourceManager.GetString("newPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no item in your shopping basket.
        /// </summary>
        internal static string noItemsInCart {
            get {
                return ResourceManager.GetString("noItemsInCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No result found the keyword you are searching.
        /// </summary>
        internal static string noResultFound {
            get {
                return ResourceManager.GetString("noResultFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your typo or try again with other keywords.
        /// </summary>
        internal static string noResultFound1 {
            get {
                return ResourceManager.GetString("noResultFound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of room.
        /// </summary>
        internal static string NoRoom {
            get {
                return ResourceManager.GetString("NoRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        internal static string notAvailable {
            get {
                return ResourceManager.GetString("notAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nights.
        /// </summary>
        internal static string numberOfDate {
            get {
                return ResourceManager.GetString("numberOfDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for visiting Aquila Booking.Your booking has been cancelled..
        /// </summary>
        internal static string orderCancelled {
            get {
                return ResourceManager.GetString("orderCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  here .
        /// </summary>
        internal static string orderHere {
            get {
                return ResourceManager.GetString("orderHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for booking with Aquila Booking. Your hotel reservation has been confirmed &amp; your payment has been partially received, Note we only recieved the 10% of the total payment. The remaining has be paid when you utilise the service(s) from the hotel..
        /// </summary>
        internal static string orderShipping {
            get {
                return ResourceManager.GetString("orderShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid amount.
        /// </summary>
        internal static string paid {
            get {
                return ResourceManager.GetString("paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was error while processing the payment. Please contact us for help or go to the pay now to make the payment again..
        /// </summary>
        internal static string paidError {
            get {
                return ResourceManager.GetString("paidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for booking with Aquila Booking. Your hotel reservation has been confirmed &amp; your payment has been partially received, Note we only recieved the 10% of the total payment. The remaining has be paid when you utilise the service(s) from the hotel..
        /// </summary>
        internal static string paidSuccessfully {
            get {
                return ResourceManager.GetString("paidSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 10 charaters length.
        /// </summary>
        internal static string passwordMinimumLength {
            get {
                return ResourceManager.GetString("passwordMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in your password.
        /// </summary>
        internal static string passwordRequired {
            get {
                return ResourceManager.GetString("passwordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Now.
        /// </summary>
        internal static string pay {
            get {
                return ResourceManager.GetString("pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay by.
        /// </summary>
        internal static string payBy {
            get {
                return ResourceManager.GetString("payBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit card.
        /// </summary>
        internal static string payByDebitCard {
            get {
                return ResourceManager.GetString("payByDebitCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string payment {
            get {
                return ResourceManager.GetString("payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Confirmation.
        /// </summary>
        internal static string paymentConfirmation {
            get {
                return ResourceManager.GetString("paymentConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to payment details.
        /// </summary>
        internal static string PaymentDetails {
            get {
                return ResourceManager.GetString("PaymentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU WOULD LIKE TO PAY BY.
        /// </summary>
        internal static string paymentMethod {
            get {
                return ResourceManager.GetString("paymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quý khách cần điền đầy đủ thông tin bên dưới.
        /// </summary>
        internal static string paymentValidation {
            get {
                return ResourceManager.GetString("paymentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the payment button to proceed the payemnt, it also mean you agree with our.
        /// </summary>
        internal static string paymentWarningMsg {
            get {
                return ResourceManager.GetString("paymentWarningMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term of Use.
        /// </summary>
        internal static string paymentWarningMsg1 {
            get {
                return ResourceManager.GetString("paymentWarningMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string paymentWarningMsg2 {
            get {
                return ResourceManager.GetString("paymentWarningMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFFLINE PAYMENT.
        /// </summary>
        internal static string payOffline {
            get {
                return ResourceManager.GetString("payOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay offline.
        /// </summary>
        internal static string payOffline1 {
            get {
                return ResourceManager.GetString("payOffline1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can make your payment by transferring to one of the listed account below: .
        /// </summary>
        internal static string payOfflineMsg {
            get {
                return ResourceManager.GetString("payOfflineMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string phoneNumber {
            get {
                return ResourceManager.GetString("phoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string previous {
            get {
                return ResourceManager.GetString("previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price from.
        /// </summary>
        internal static string priceFrom {
            get {
                return ResourceManager.GetString("priceFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string PriceHotel {
            get {
                return ResourceManager.GetString("PriceHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air ticket.
        /// </summary>
        internal static string purchaseAirTicket {
            get {
                return ResourceManager.GetString("purchaseAirTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add into compare list?.
        /// </summary>
        internal static string QuestionComparelist {
            get {
                return ResourceManager.GetString("QuestionComparelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more.
        /// </summary>
        internal static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill the below information to register.
        /// </summary>
        internal static string registerMsg {
            get {
                return ResourceManager.GetString("registerMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you do not have account please click.
        /// </summary>
        internal static string registerMsgReminder {
            get {
                return ResourceManager.GetString("registerMsgReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập lại.
        /// </summary>
        internal static string relogon {
            get {
                return ResourceManager.GetString("relogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        internal static string remark {
            get {
                return ResourceManager.GetString("remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string rememberMe {
            get {
                return ResourceManager.GetString("rememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from comparation list.
        /// </summary>
        internal static string removeFromCompareList {
            get {
                return ResourceManager.GetString("removeFromCompareList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from commpare list.
        /// </summary>
        internal static string removeToCompareList {
            get {
                return ResourceManager.GetString("removeToCompareList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        internal static string resetPassword {
            get {
                return ResourceManager.GetString("resetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email to reset your password.
        /// </summary>
        internal static string resetPasswordMsg {
            get {
                return ResourceManager.GetString("resetPasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mật khẩu thành công.
        /// </summary>
        internal static string resetPasswordSuccessfully {
            get {
                return ResourceManager.GetString("resetPasswordSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu của Quý khách đã được tạo lại thành công. Mật khẩu mới đã được gửi vào hộp thư của Quý khách. Vui lòng kiểm tra email để biết thông tin mật khẩu mới..
        /// </summary>
        internal static string resetPasswordSuccessMessage {
            get {
                return ResourceManager.GetString("resetPasswordSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        internal static string review {
            get {
                return ResourceManager.GetString("review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string ReviewHotel {
            get {
                return ResourceManager.GetString("ReviewHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your comment.
        /// </summary>
        internal static string reviewValidation {
            get {
                return ResourceManager.GetString("reviewValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room type.
        /// </summary>
        internal static string RoomType {
            get {
                return ResourceManager.GetString("RoomType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string saveReview {
            get {
                return ResourceManager.GetString("saveReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment saved.
        /// </summary>
        internal static string saveReviewSuccess {
            get {
                return ResourceManager.GetString("saveReviewSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to says:.
        /// </summary>
        internal static string say {
            get {
                return ResourceManager.GetString("say", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết sổ cổ đông.
        /// </summary>
        internal static string searchCurrentBalance {
            get {
                return ResourceManager.GetString("searchCurrentBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchDestination {
            get {
                return ResourceManager.GetString("SearchDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for.
        /// </summary>
        internal static string searchFor {
            get {
                return ResourceManager.GetString("searchFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm lịch sử giao dịch.
        /// </summary>
        internal static string searchHint {
            get {
                return ResourceManager.GetString("searchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê số dư.
        /// </summary>
        internal static string searchSummaryCurrentBalance {
            get {
                return ResourceManager.GetString("searchSummaryCurrentBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check price of hotel.
        /// </summary>
        internal static string searchTitle {
            get {
                return ResourceManager.GetString("searchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm giao dịch.
        /// </summary>
        internal static string searchTradingTransaction {
            get {
                return ResourceManager.GetString("searchTradingTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the check-in and check-out date.
        /// </summary>
        internal static string searchWarning {
            get {
                return ResourceManager.GetString("searchWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem tất cả.
        /// </summary>
        internal static string selectAllOption {
            get {
                return ResourceManager.GetString("selectAllOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bán.
        /// </summary>
        internal static string sell {
            get {
                return ResourceManager.GetString("sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi.
        /// </summary>
        internal static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VFS - Thông báo.
        /// </summary>
        internal static string senderName {
            get {
                return ResourceManager.GetString("senderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service name.
        /// </summary>
        internal static string serviceName {
            get {
                return ResourceManager.GetString("serviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and book on our website to make comment.
        /// </summary>
        internal static string serviceNeeded {
            get {
                return ResourceManager.GetString("serviceNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số CĐ CN.
        /// </summary>
        internal static string shareHolderCode {
            get {
                return ResourceManager.GetString("shareHolderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã cổ đông.
        /// </summary>
        internal static string shareHolderCode01 {
            get {
                return ResourceManager.GetString("shareHolderCode01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên cổ đông.
        /// </summary>
        internal static string shareHolderName {
            get {
                return ResourceManager.GetString("shareHolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã cổ phiếu.
        /// </summary>
        internal static string shareSymbol {
            get {
                return ResourceManager.GetString("shareSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã cổ phiếu/Mã cổ đông.
        /// </summary>
        internal static string shareSymbolOrShareHolder {
            get {
                return ResourceManager.GetString("shareSymbolOrShareHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping cart.
        /// </summary>
        internal static string shoppingCart {
            get {
                return ResourceManager.GetString("shoppingCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking history.
        /// </summary>
        internal static string ShortCheckingHotelBooking {
            get {
                return ResourceManager.GetString("ShortCheckingHotelBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string signUp {
            get {
                return ResourceManager.GetString("signUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số CMND.
        /// </summary>
        internal static string ssn {
            get {
                return ResourceManager.GetString("ssn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        internal static string StarAverage {
            get {
                return ResourceManager.GetString("StarAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execellent.
        /// </summary>
        internal static string StarExecellent {
            get {
                return ResourceManager.GetString("StarExecellent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poor.
        /// </summary>
        internal static string StarPoor {
            get {
                return ResourceManager.GetString("StarPoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrible.
        /// </summary>
        internal static string StarTerrible {
            get {
                return ResourceManager.GetString("StarTerrible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very good.
        /// </summary>
        internal static string StarVerygood {
            get {
                return ResourceManager.GetString("StarVerygood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập hệ thống.
        /// </summary>
        internal static string systemLogOn {
            get {
                return ResourceManager.GetString("systemLogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term of use.
        /// </summary>
        internal static string termOfUse {
            get {
                return ResourceManager.GetString("termOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-out.
        /// </summary>
        internal static string toDate {
            get {
                return ResourceManager.GetString("toDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày về.
        /// </summary>
        internal static string ToDate1 {
            get {
                return ResourceManager.GetString("ToDate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to register.
        /// </summary>
        internal static string toRegister {
            get {
                return ResourceManager.GetString("toRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount.
        /// </summary>
        internal static string totalAmount {
            get {
                return ResourceManager.GetString("totalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Payment.
        /// </summary>
        internal static string totalPayment {
            get {
                return ResourceManager.GetString("totalPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total room.
        /// </summary>
        internal static string totalRoom {
            get {
                return ResourceManager.GetString("totalRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số.
        /// </summary>
        internal static string transactionNumber {
            get {
                return ResourceManager.GetString("transactionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THÔNG TIN DU LỊCH.
        /// </summary>
        internal static string TravelInfo {
            get {
                return ResourceManager.GetString("TravelInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại hình.
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu thay đổi không thành công..
        /// </summary>
        internal static string unsuccessfulPasswordChange {
            get {
                return ResourceManager.GetString("unsuccessfulPasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT.
        /// </summary>
        internal static string vat {
            get {
                return ResourceManager.GetString("vat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem.
        /// </summary>
        internal static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhấp chuột để xem thông tin.
        /// </summary>
        internal static string viewHint {
            get {
                return ResourceManager.GetString("viewHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Search.
        /// </summary>
        internal static string WhereAndCheckRoom {
            get {
                return ResourceManager.GetString("WhereAndCheckRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your booking code.
        /// </summary>
        internal static string yourBookingCode {
            get {
                return ResourceManager.GetString("yourBookingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your booking details.
        /// </summary>
        internal static string yourBookingDetails {
            get {
                return ResourceManager.GetString("yourBookingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your comment.
        /// </summary>
        internal static string yourReview {
            get {
                return ResourceManager.GetString("yourReview", resourceCulture);
            }
        }
    }
}
