//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserInterface {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserInterface() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.UserInterface", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số dư.
        /// </summary>
        internal static string balanceQuantity {
            get {
                return ResourceManager.GetString("balanceQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số dư đầu kỳ.
        /// </summary>
        internal static string beginBalance {
            get {
                return ResourceManager.GetString("beginBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mua.
        /// </summary>
        internal static string buy {
            get {
                return ResourceManager.GetString("buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquila System thông báo: Thay đổi mật khẩu.
        /// </summary>
        internal static string changePassEmailSubject {
            get {
                return ResourceManager.GetString("changePassEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi mật khẩu.
        /// </summary>
        internal static string changePassword {
            get {
                return ResourceManager.GetString("changePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu thành công.
        /// </summary>
        internal static string changePasswordSuccessfully {
            get {
                return ResourceManager.GetString("changePasswordSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu của Quý khách đã được thay đổi thành công. Mật khẩu mới đã được gửi vào hộp thư của Quý khách. Vui lòng kiểm tra email để biết thông tin mật khẩu mới..
        /// </summary>
        internal static string changePasswordSuccessMessage {
            get {
                return ResourceManager.GetString("changePasswordSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tăng.
        /// </summary>
        internal static string creditDescription {
            get {
                return ResourceManager.GetString("creditDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người mua.
        /// </summary>
        internal static string creditShareHolderCode {
            get {
                return ResourceManager.GetString("creditShareHolderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người mua.
        /// </summary>
        internal static string creditShareHolderName {
            get {
                return ResourceManager.GetString("creditShareHolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giảm.
        /// </summary>
        internal static string debitDescription {
            get {
                return ResourceManager.GetString("debitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người bán.
        /// </summary>
        internal static string debitShareHolderCode {
            get {
                return ResourceManager.GetString("debitShareHolderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người bán.
        /// </summary>
        internal static string debitShareHolderName {
            get {
                return ResourceManager.GetString("debitShareHolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2012 - Công ty cổ phần Chứng Khoán Nhất Việt.
        /// </summary>
        internal static string footerText {
            get {
                return ResourceManager.GetString("footerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu?.
        /// </summary>
        internal static string forgotpassword {
            get {
                return ResourceManager.GetString("forgotpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày.
        /// </summary>
        internal static string fromDate {
            get {
                return ResourceManager.GetString("fromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Về trước.
        /// </summary>
        internal static string goBack {
            get {
                return ResourceManager.GetString("goBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhấp chuột để  về trước.
        /// </summary>
        internal static string goBackHint {
            get {
                return ResourceManager.GetString("goBackHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng dẫn sử dụng.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chính - Aquila.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập hoặc mật khẩu không đúng..
        /// </summary>
        internal static string incorrectUserNamePassword {
            get {
                return ResourceManager.GetString("incorrectUserNamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ không đúng.
        /// </summary>
        internal static string InvalidOldPassword {
            get {
                return ResourceManager.GetString("InvalidOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát.
        /// </summary>
        internal static string logOff {
            get {
                return ResourceManager.GetString("logOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhấp chuột để đăng xuất.
        /// </summary>
        internal static string logOffHint {
            get {
                return ResourceManager.GetString("logOffHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        internal static string logOn {
            get {
                return ResourceManager.GetString("logOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập không thành công. Quý khách vui lòng nhập đầy đủ thông tin phía dưới..
        /// </summary>
        internal static string logonFailed {
            get {
                return ResourceManager.GetString("logonFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhấp chuột để đăng nhập.
        /// </summary>
        internal static string logonHint {
            get {
                return ResourceManager.GetString("logonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin tài khoản đăng nhập.
        /// </summary>
        internal static string myProfile {
            get {
                return ResourceManager.GetString("myProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đăng nhập.
        /// </summary>
        internal static string myProfile1 {
            get {
                return ResourceManager.GetString("myProfile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        internal static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập lại.
        /// </summary>
        internal static string relogon {
            get {
                return ResourceManager.GetString("relogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        internal static string remark {
            get {
                return ResourceManager.GetString("remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm lại mật khẩu.
        /// </summary>
        internal static string resetPassword {
            get {
                return ResourceManager.GetString("resetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mật khẩu thành công.
        /// </summary>
        internal static string resetPasswordSuccessfully {
            get {
                return ResourceManager.GetString("resetPasswordSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu của Quý khách đã được tạo lại thành công. Mật khẩu mới đã được gửi vào hộp thư của Quý khách. Vui lòng kiểm tra email để biết thông tin mật khẩu mới..
        /// </summary>
        internal static string resetPasswordSuccessMessage {
            get {
                return ResourceManager.GetString("resetPasswordSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết sổ cổ đông.
        /// </summary>
        internal static string searchCurrentBalance {
            get {
                return ResourceManager.GetString("searchCurrentBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm lịch sử giao dịch.
        /// </summary>
        internal static string searchHint {
            get {
                return ResourceManager.GetString("searchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê số dư.
        /// </summary>
        internal static string searchSummaryCurrentBalance {
            get {
                return ResourceManager.GetString("searchSummaryCurrentBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm giao dịch.
        /// </summary>
        internal static string searchTradingTransaction {
            get {
                return ResourceManager.GetString("searchTradingTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem tất cả.
        /// </summary>
        internal static string selectAllOption {
            get {
                return ResourceManager.GetString("selectAllOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bán.
        /// </summary>
        internal static string sell {
            get {
                return ResourceManager.GetString("sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi.
        /// </summary>
        internal static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VFS - Thông báo.
        /// </summary>
        internal static string senderName {
            get {
                return ResourceManager.GetString("senderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số CĐ CN.
        /// </summary>
        internal static string shareHolderCode {
            get {
                return ResourceManager.GetString("shareHolderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã cổ đông.
        /// </summary>
        internal static string shareHolderCode01 {
            get {
                return ResourceManager.GetString("shareHolderCode01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên cổ đông.
        /// </summary>
        internal static string shareHolderName {
            get {
                return ResourceManager.GetString("shareHolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã cổ phiếu.
        /// </summary>
        internal static string shareSymbol {
            get {
                return ResourceManager.GetString("shareSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã cổ phiếu/Mã cổ đông.
        /// </summary>
        internal static string shareSymbolOrShareHolder {
            get {
                return ResourceManager.GetString("shareSymbolOrShareHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số CMND.
        /// </summary>
        internal static string ssn {
            get {
                return ResourceManager.GetString("ssn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập hệ thống.
        /// </summary>
        internal static string systemLogOn {
            get {
                return ResourceManager.GetString("systemLogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến ngày.
        /// </summary>
        internal static string toDate {
            get {
                return ResourceManager.GetString("toDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số.
        /// </summary>
        internal static string transactionNumber {
            get {
                return ResourceManager.GetString("transactionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại hình.
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu thay đổi không thành công..
        /// </summary>
        internal static string unsuccessfulPasswordChange {
            get {
                return ResourceManager.GetString("unsuccessfulPasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem.
        /// </summary>
        internal static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhấp chuột để xem thông tin.
        /// </summary>
        internal static string viewHint {
            get {
                return ResourceManager.GetString("viewHint", resourceCulture);
            }
        }
    }
}
