//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserInterfaceVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserInterfaceVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.UserInterfaceVN", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng tôi.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ: .
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết đặt phòng.
        /// </summary>
        internal static string BookingDetails {
            get {
                return ResourceManager.GetString("BookingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt phòng.
        /// </summary>
        internal static string Booknow {
            get {
                return ResourceManager.GetString("Booknow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIỎ HÀNG.
        /// </summary>
        internal static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click vào đây để kiểm tra lịch sử đặt phòng.
        /// </summary>
        internal static string CheckingHotelBooking {
            get {
                return ResourceManager.GetString("CheckingHotelBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bình luận.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SO SÁNH.
        /// </summary>
        internal static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục so sánh.
        /// </summary>
        internal static string CompareList {
            get {
                return ResourceManager.GetString("CompareList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIÊN HỆ.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm đến của bạn: .
        /// </summary>
        internal static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết phòng đang đặt.
        /// </summary>
        internal static string DetailBooking {
            get {
                return ResourceManager.GetString("DetailBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết khách sạn .
        /// </summary>
        internal static string DetailHotel {
            get {
                return ResourceManager.GetString("DetailHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email bị trùng hoặc không đúng định dạng, ví dụ: abc@xyz.com.
        /// </summary>
        internal static string ErrorEmail {
            get {
                return ResourceManager.GetString("ErrorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỏi &amp; Đáp.
        /// </summary>
        internal static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm đến yêu thích.
        /// </summary>
        internal static string FavouritDestination {
            get {
                return ResourceManager.GetString("FavouritDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên .
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày đi: .
        /// </summary>
        internal static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRỢ GIÚP.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trợ giúp từ Aquila.
        /// </summary>
        internal static string HelpFromUs {
            get {
                return ResourceManager.GetString("HelpFromUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANG CHỦ.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khách sạn.
        /// </summary>
        internal static string HotelName {
            get {
                return ResourceManager.GetString("HotelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sao.
        /// </summary>
        internal static string HotelStar {
            get {
                return ResourceManager.GetString("HotelStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách sạn được xem gần nhất.
        /// </summary>
        internal static string HotelViewlastest {
            get {
                return ResourceManager.GetString("HotelViewlastest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LangE {
            get {
                return ResourceManager.GetString("LangE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng việt.
        /// </summary>
        internal static string LangV {
            get {
                return ResourceManager.GetString("LangV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ .
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DANH MỤC PHÒNG.
        /// </summary>
        internal static string ListRoom {
            get {
                return ResourceManager.GetString("ListRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So sánh.
        /// </summary>
        internal static string LowerCompare {
            get {
                return ResourceManager.GetString("LowerCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tối đa.
        /// </summary>
        internal static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách sạn được ưa chuộng.
        /// </summary>
        internal static string MostView {
            get {
                return ResourceManager.GetString("MostView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn số phòng.
        /// </summary>
        internal static string NoRoom {
            get {
                return ResourceManager.GetString("NoRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết thanh toán.
        /// </summary>
        internal static string PaymentDetails {
            get {
                return ResourceManager.GetString("PaymentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá phòng.
        /// </summary>
        internal static string PriceHotel {
            get {
                return ResourceManager.GetString("PriceHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn thêm khách sạn vào danh mục so sánh.
        /// </summary>
        internal static string QuestionComparelist {
            get {
                return ResourceManager.GetString("QuestionComparelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem thêm.
        /// </summary>
        internal static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lượt xem.
        /// </summary>
        internal static string ReviewHotel {
            get {
                return ResourceManager.GetString("ReviewHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại phòng.
        /// </summary>
        internal static string RoomType {
            get {
                return ResourceManager.GetString("RoomType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm.
        /// </summary>
        internal static string SearchDestination {
            get {
                return ResourceManager.GetString("SearchDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sử đặt phòng.
        /// </summary>
        internal static string ShortCheckingHotelBooking {
            get {
                return ResourceManager.GetString("ShortCheckingHotelBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày về: .
        /// </summary>
        internal static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THÔNG TIN DU LỊCH.
        /// </summary>
        internal static string TravelInfo {
            get {
                return ResourceManager.GetString("TravelInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểm tra giá và phòng.
        /// </summary>
        internal static string WhereAndCheckRoom {
            get {
                return ResourceManager.GetString("WhereAndCheckRoom", resourceCulture);
            }
        }
    }
}
