//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhimHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.Group_User = new HashSet<Group_User>();
            this.Group_User_Messege = new HashSet<Group_User_Messege>();
        }
    
        public int GroupId { get; set; }
        public string GroupName { get; set; }
        public string GroupType { get; set; }
    
        public virtual ICollection<Group_User> Group_User { get; set; }
        public virtual ICollection<Group_User_Messege> Group_User_Messege { get; set; }
    }
}
