//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhimHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group_User
    {
        public long Id { get; set; }
        public int GroupId { get; set; }
        public int UserOfGroup { get; set; }
        public Nullable<int> TopPosition { get; set; }
        public Nullable<int> LeftPosition { get; set; }
        public Nullable<bool> Reviced { get; set; }
        public Nullable<bool> WindowLoad { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual UserLogin UserLogin { get; set; }
    }
}
