//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhimHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public UserLogin()
        {
            this.Group_User = new HashSet<Group_User>();
            this.Group_User_Messege = new HashSet<Group_User_Messege>();
        }
    
        public int Id { get; set; }
        public string KeyLogin { get; set; }
        public string UserNameCopy { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string AvataImage { get; set; }
        public string AvataCover { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Verify { get; set; }
        public int AccountType { get; set; }
        public int LockAccount { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Group_User> Group_User { get; set; }
        public virtual ICollection<Group_User_Messege> Group_User_Messege { get; set; }
    }
}
