//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhimHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationMessege
    {
        public long ID { get; set; }
        public int UserPost { get; set; }
        public int UserReciver { get; set; }
        public Nullable<long> PostId { get; set; }
        public Nullable<int> NumNoti { get; set; }
        public string TypeNoti { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<bool> XemYN { get; set; }
    
        public virtual UserLogin UserLogin { get; set; }
        public virtual UserLogin UserLogin1 { get; set; }
        public virtual Post Post { get; set; }
    }
}
