//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhimHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Philosophy
    {
        public Philosophy()
        {
            this.UserLogins = new HashSet<UserLogin>();
        }
    
        public byte Id { get; set; }
        public string PhilosophyName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual ICollection<UserLogin> UserLogins { get; set; }
    }
}
