//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockPriceSynEverydate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stox_tb_MarketInfo
    {
        public long ID { get; set; }
        public string FLOOR_CODE { get; set; }
        public Nullable<int> DATE_NO { get; set; }
        public System.DateTime TRADING_DATE { get; set; }
        public Nullable<int> CURRENT_STATUS { get; set; }
        public string TIME { get; set; }
        public Nullable<int> TOTAL_TRADE { get; set; }
        public Nullable<int> TOTAL_STOCK { get; set; }
        public Nullable<decimal> TOTAL_QTTY { get; set; }
        public Nullable<decimal> TOTAL_VALUE { get; set; }
        public Nullable<int> ADVANCES { get; set; }
        public Nullable<int> NOCHANGE { get; set; }
        public Nullable<int> DECLINES { get; set; }
        public Nullable<decimal> PRIOR_MARKET_INDEX { get; set; }
        public Nullable<decimal> CHG_INDEX { get; set; }
        public Nullable<decimal> PCT_INDEX { get; set; }
        public Nullable<decimal> CURRENT_INDEX { get; set; }
        public decimal MARKET_INDEX { get; set; }
        public Nullable<decimal> SESSION_NO { get; set; }
        public Nullable<decimal> PRV_PRIOR_MARKET_INDEX { get; set; }
        public Nullable<decimal> AVR_MARKET_INDEX { get; set; }
        public Nullable<decimal> AVR_PRIOR_MARKET_INDEX { get; set; }
        public Nullable<decimal> AVR_CHG_INDEX { get; set; }
        public Nullable<decimal> AVR_PCT_INDEX { get; set; }
        public Nullable<decimal> PT_TOTAL_QTTY { get; set; }
        public Nullable<decimal> PT_TOTAL_VALUE { get; set; }
        public Nullable<decimal> PT_TOTAL_TRADE { get; set; }
        public Nullable<System.DateTime> DATE_REPORT { get; set; }
        public Nullable<decimal> LOWEST { get; set; }
        public Nullable<decimal> HIGHTEST { get; set; }
        public Nullable<decimal> OPEN_INDEX { get; set; }
    }
}
