//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyURL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class URLTiny
    {
        public string Id { get; set; }
        public string URLName { get; set; }
        public System.DateTime PostedDate { get; set; }
    }
}
