//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhimHang.vn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostComment
    {
        public long PostCommentsId { get; set; }
        public string Message { get; set; }
        public long PostedBy { get; set; }
        public int CommentBy { get; set; }
        public System.DateTime PostedDate { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual UserLogin UserLogin { get; set; }
    }
}
