//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhimHang.vn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public long PostId { get; set; }
        public string Message { get; set; }
        public string PostedBy { get; set; }
        public System.DateTime PostedDate { get; set; }
        public string ChartImageURL { get; set; }
        public Nullable<int> NhanDinh { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
