//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhimHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRelate
    {
        public long ID { get; set; }
        public int UserId { get; set; }
        public Nullable<long> PostId { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual UserLogin UserLogin { get; set; }
    }
}
