//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhimHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public UserLogin()
        {
            this.FollowStocks = new HashSet<FollowStock>();
            this.FollowUsers = new HashSet<FollowUser>();
            this.FollowUsers1 = new HashSet<FollowUser>();
            this.PostComments = new HashSet<PostComment>();
            this.Posts = new HashSet<Post>();
            this.StockViewLastests = new HashSet<StockViewLastest>();
            this.UserRelates = new HashSet<UserRelate>();
            this.UserViewLastests = new HashSet<UserViewLastest>();
            this.UserViewLastests1 = new HashSet<UserViewLastest>();
        }
    
        public int Id { get; set; }
        public string KeyLogin { get; set; }
    
        public virtual ICollection<FollowStock> FollowStocks { get; set; }
        public virtual ICollection<FollowUser> FollowUsers { get; set; }
        public virtual ICollection<FollowUser> FollowUsers1 { get; set; }
        public virtual ICollection<PostComment> PostComments { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<StockViewLastest> StockViewLastests { get; set; }
        public virtual ICollection<UserRelate> UserRelates { get; set; }
        public virtual ICollection<UserViewLastest> UserViewLastests { get; set; }
        public virtual ICollection<UserViewLastest> UserViewLastests1 { get; set; }
    }
}
