//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareHolderCore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShareHolderCore.ValidationMessage", typeof(ValidationMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vốn điều lệ: từ  100,000,000 đến 1000000000000000.
        /// </summary>
        internal static string capital {
            get {
                return ResourceManager.GetString("capital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tên công ty tối thiểu 6 ký tự.
        /// </summary>
        internal static string companyName {
            get {
                return ResourceManager.GetString("companyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày phát hành theo định dạng : ngày/tháng/năm (dd/mm/yyyy).
        /// </summary>
        internal static string dataTime {
            get {
                return ResourceManager.GetString("dataTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản có duyệt hay không?.
        /// </summary>
        internal static string IsApproved {
            get {
                return ResourceManager.GetString("IsApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản có hoạt động không?.
        /// </summary>
        internal static string isLockedOut {
            get {
                return ResourceManager.GetString("isLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mã ngôn ngữ.
        /// </summary>
        internal static string languageID {
            get {
                return ResourceManager.GetString("languageID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày đăng nhập gần nhất theo định dạng : ngày/tháng/năm (dd/mm/yyyy).
        /// </summary>
        internal static string lastLoginDate {
            get {
                return ResourceManager.GetString("lastLoginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đăng nhập phải có ít nhất 6 ký tự.
        /// </summary>
        internal static string loginId {
            get {
                return ResourceManager.GetString("loginId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tên tối thiểu 3 ký tự, dài nhất 14 ký tự.
        /// </summary>
        internal static string nameBank {
            get {
                return ResourceManager.GetString("nameBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập họ và tên cổ đông.
        /// </summary>
        internal static string nameHolder {
            get {
                return ResourceManager.GetString("nameHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        internal static string note {
            get {
                return ResourceManager.GetString("note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu phải ít nhất 6 ký tự.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng khối lượng giao dịch.
        /// </summary>
        internal static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mã cổ đông.
        /// </summary>
        internal static string shareHolderCode {
            get {
                return ResourceManager.GetString("shareHolderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn nhóm tài khoản trong danh sách.
        /// </summary>
        internal static string shareHolderGroupId {
            get {
                return ResourceManager.GetString("shareHolderGroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phải nhập mã cổ đông.
        /// </summary>
        internal static string shareHolderId {
            get {
                return ResourceManager.GetString("shareHolderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mã cổ phiếu tối thiểu 3 ký tự.
        /// </summary>
        internal static string shareSymbol {
            get {
                return ResourceManager.GetString("shareSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn loại cổ phiếu trong danh mục.
        /// </summary>
        internal static string shareTypeId {
            get {
                return ResourceManager.GetString("shareTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểu chuyện nhượng.
        /// </summary>
        internal static string shareTypeName {
            get {
                return ResourceManager.GetString("shareTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tình trạng.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng số lượng cổ phiếu lưu hành: từ 0 đến 10,000,000,000.
        /// </summary>
        internal static string totalShare {
            get {
                return ResourceManager.GetString("totalShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn kiểu chuyện nhượng.
        /// </summary>
        internal static string transactionCategoryId {
            get {
                return ResourceManager.GetString("transactionCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phải có mã giao dịch.
        /// </summary>
        internal static string transactionId {
            get {
                return ResourceManager.GetString("transactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn loại giao dịch trong danh sách.
        /// </summary>
        internal static string transactionType {
            get {
                return ResourceManager.GetString("transactionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên của tài khoản phải có 6 ký tự.
        /// </summary>
        internal static string userName {
            get {
                return ResourceManager.GetString("userName", resourceCulture);
            }
        }
    }
}
