//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PorfolioInvesment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stox_tb_Company
    {
        public int ID { get; set; }
        public string Ticker { get; set; }
        public string ShortName { get; set; }
        public string Name { get; set; }
    }
}
