//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PorfolioInvesment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stox_tb_HOSE_Trading
    {
        public long ID { get; set; }
        public string StockSymbol { get; set; }
        public Nullable<decimal> Ceiling { get; set; }
        public Nullable<decimal> Floor { get; set; }
        public Nullable<decimal> PriorClosePrice { get; set; }
        public Nullable<decimal> OpenPrice { get; set; }
        public Nullable<decimal> Last { get; set; }
        public Nullable<decimal> Highest { get; set; }
        public Nullable<decimal> Lowest { get; set; }
        public Nullable<System.DateTime> DateReport { get; set; }
    }
}
