//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PorfolioInvesment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stox_tb_HOSE_TotalTrading
    {
        public long ID { get; set; }
        public Nullable<decimal> VNIndex { get; set; }
        public Nullable<System.DateTime> DateReport { get; set; }
        public Nullable<decimal> PreVNIndex { get; set; }
        public Nullable<decimal> Lowest { get; set; }
        public Nullable<decimal> Hightest { get; set; }
        public Nullable<decimal> OpenIndex { get; set; }
    }
}
