//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PorfolioInvesment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stox_tb_StocksInfo
    {
        public long ID { get; set; }
        public System.DateTime trading_date { get; set; }
        public string code { get; set; }
        public byte stock_type { get; set; }
        public Nullable<decimal> basic_price { get; set; }
        public Nullable<decimal> open_price { get; set; }
        public Nullable<decimal> close_price { get; set; }
        public Nullable<decimal> highest_price { get; set; }
        public Nullable<decimal> lowest_price { get; set; }
        public Nullable<decimal> ceiling_price { get; set; }
        public Nullable<decimal> floor_price { get; set; }
    }
}
